// Generated by CoffeeScript 1.3.3
(function() {
  var App;

  App = (function() {

    function App(params) {
      return;
    }

    App.prototype.init = function() {};

    return App;

  })();

  window.App = App;

}).call(this);
